apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: httpd_app_xfusion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app_xfusion
  template:
    metadata:
      labels:
        app: httpd_app_xfusion
    spec:
      containers:
        - name: httpd-container-xfusion
          image: httpd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
