apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    svc: apache_service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: apache_webserver
